import HTMLHead from 'next/head'

const Head = () => (
  <HTMLHead>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </HTMLHead>
);

const Body = () => (
  <main className="container max-w-4xl m-auto px-3">
    <h1 className="text-3xl font-bold">
      Welcome to <a href="https://nextjs.org">Next.js!</a>
    </h1>
  </main>
);

export { Head, Body };